django_pos/customers/urls.py
from django.urls import path

from . import views

app_name = "customers"
urlpatterns = [
    # List customers
    path('', views.CustomersListView, name='customers_list'),
    # Add customer
    path('add', views.CustomersAddView, name='customers_add'),
    # Update customer
    path('update/<str:customer_id>',
         views.CustomersUpdateView, name='customers_update'),
    # Delete customer
    path('delete/<str:customer_id>',
         views.CustomersDeleteView, name='customers_delete'),
]

django_pos/django_pos/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
    # Authentication: Login and Logout
    path('', include('authentication.urls')),
    # Index
    path('', include('pos.urls')),
    # Products
    path('products/', include('products.urls')),
    # Customers
    path('customers/', include('customers.urls')),
    # Sales
    path('sales/', include('sales.urls')),
]

django_pos/pos/urls.py
from django.urls import path

from . import views

app_name = "pos"
urlpatterns = [
    path('', views.index, name='index'),
]

django_pos/customers/models.py
from django.db import models
from django.forms import model_to_dict


class Customer(models.Model):
    first_name = models.CharField(max_length=256)
    last_name = models.CharField(max_length=256, blank=True, null=True)
    address = models.TextField(max_length=256, blank=True, null=True)
    email = models.EmailField(max_length=256, blank=True, null=True)
    phone = models.CharField(max_length=30, blank=True, null=True)

    class Meta:
        db_table = 'Customers'

    def __str__(self) -> str:
        return self.first_name + " " + self.last_name

    def get_full_name(self):
        return self.first_name + " " + self.last_name

    def to_select2(self):
        item = {
            "label": self.get_full_name(),
            "value": self.id
        }
        return item

django_pos/customers/views.py
from django.contrib import messages
from django.contrib.auth.decorators import login_required
from django.shortcuts import render, redirect
from .models import Customer


@login_required(login_url="/accounts/login/")
def CustomersListView(request):
    context = {
        "active_icon": "customers",
        "customers": Customer.objects.all()
    }
    return render(request, "customers/customers.html", context=context)


@login_required(login_url="/accounts/login/")
def CustomersAddView(request):
    context = {
        "active_icon": "customers",
    }

    if request.method == 'POST':
        # Save the POST arguements
        data = request.POST

        attributes = {
            "first_name": data['first_name'],
            "last_name": data['last_name'],
            "address": data['address'],
            "email": data['email'],
            "phone": data['phone'],
        }

        # Check if a customer with the same attributes exists
        if Customer.objects.filter(**attributes).exists():
            messages.error(request, 'Customer already exists!',
                           extra_tags="warning")
            return redirect('customers:customers_add')

        try:
            # Create the customer
            new_customer = Customer.objects.create(**attributes)

            # If it doesn't exists save it
            new_customer.save()

            messages.success(request, 'Customer: ' + attributes["first_name"] + " " +
                             attributes["last_name"] + ' created succesfully!', extra_tags="success")
            return redirect('customers:customers_list')
        except Exception as e:
            messages.success(
                request, 'There was an error during the creation!', extra_tags="danger")
            print(e)
            return redirect('customers:customers_add')

    return render(request, "customers/customers_add.html", context=context)


@login_required(login_url="/accounts/login/")
def CustomersUpdateView(request, customer_id):
    """
    Args:
        customer_id : The customer's ID that will be updated
    """

    # Get the customer
    try:
        # Get the customer to update
        customer = Customer.objects.get(id=customer_id)
    except Exception as e:
        messages.success(
            request, 'There was an error trying to get the customer!', extra_tags="danger")
        print(e)
        return redirect('customers:customers_list')

    context = {
        "active_icon": "customers",
        "customer": customer,
    }

    if request.method == 'POST':
        try:
            # Save the POST arguements
            data = request.POST

            attributes = {
                "first_name": data['first_name'],
                "last_name": data['last_name'],
                "address": data['address'],
                "email": data['email'],
                "phone": data['phone'],
            }

            # Check if a customer with the same attributes exists
            if Customer.objects.filter(**attributes).exists():
                messages.error(request, 'Customer already exists!',
                               extra_tags="warning")
                return redirect('customers:customers_add')

            # Get the customer to update
            customer = Customer.objects.filter(
                id=customer_id).update(**attributes)

            customer = Customer.objects.get(id=customer_id)

            messages.success(request, '¡Customer: ' + customer.get_full_name() +
                             ' updated successfully!', extra_tags="success")
            return redirect('customers:customers_list')
        except Exception as e:
            messages.success(
                request, 'There was an error during the update!', extra_tags="danger")
            print(e)
            return redirect('customers:customers_list')

    return render(request, "customers/customers_update.html", context=context)


@login_required(login_url="/accounts/login/")
def CustomersDeleteView(request, customer_id):
    """
    Args:
        customer_id : The customer's ID that will be deleted
    """
    try:
        # Get the customer to delete
        customer = Customer.objects.get(id=customer_id)
        customer.delete()
        messages.success(request, '¡Customer: ' + customer.get_full_name() +
                         ' deleted!', extra_tags="success")
        return redirect('customers:customers_list')
    except Exception as e:
        messages.success(
            request, 'There was an error during the elimination!', extra_tags="danger")
        print(e)
        return redirect('customers:customers_list')

django_pos/templates/customers/customers.html
{% extends "pos/base.html" %}
{% load static %}
<!-- Page title  -->
{% block title %}Customers{% endblock title %}

<!-- Specific Page CSS goes HERE  -->
{% block stylesheets %}
<!-- Datatables -->
<link href="{% static 'vendor/datatables/dataTables.bootstrap4.min.css ' %}" rel="stylesheet">
<link href="{% static 'css/pagination_buttons.css ' %}" rel="stylesheet">
{% endblock stylesheets %}

<!-- Page Heading -->
{% block heading %}Customers{% endblock heading %}

<!-- Page content  -->
{% block content %}

    <!--Create new customer-->
    <div class="row ml-0 mb-3">
        <a href="{% url 'customers:customers_add' %}">
            <button type="button" class="btn btn-success font-weight-bold">
                    <i class="fas fa-plus mr-2"></i>
                    Create new customer
            </button>
        </a>
    </div>

    <!-- DataTable -->
    <div class="card shadow mb-12">
        <div class="card-header py-3">
            <h6 class="m-0 font-weight-bold text-primary">Customers</h6>
        </div>
        <div class="card-body">
            <div class="table-responsive">
                <table class="table table-bordered table-hover" id="dataTable" width="100%" cellspacing="0">
                    <thead>
                        <tr>
                            <th>ID</th>
                            <th style="width:5%">#</th>
                            <th style="width:20%">Name</th>
                            <th style="width:25%">Email</th>
                            <th style="width:15%">Phone</th>
                            <th style="width:25%">Adress</th>
                            <th class="text-center" style="width:10%">Actions</th>
                        </tr>
                    </thead>
                    <tbody>
                        {% for c in customers %}
                        <tr>
                            <td>{{c.id}}</td>
                            <td>{{forloop.counter}}</td>
                            <td>{{c.get_full_name}}</td>
                            <td>{{c.email}}</td>
                            <td>{{c.phone}}</td>
                            <td>{{c.address}}</td>
                            <td class="text-center">
                                <!--Update-->
                                <a href="{% url 'customers:customers_update' c.id %}" class="text-decoration-none">
                                    <button type="button" class="btn btn-warning btn-sm" data-bs-toggle="tooltip" title="Update customer">
                                        <i class="fas fa-pen"></i>
                                    </button>
                                </a>
                                <!--Delete modal-->
                                <!-- Button trigger modal -->
                                <a class="text-decoration-none">
                                    <button rel="delete" type="button" class="btn btn-danger btn-sm" data-toggle="modal" data-target="#exampleModal">
                                        <i class="fas fa-trash"></i>
                                    </button>
                                </a>
                                    
                                <!-- Modal -->
                                <div class="modal fade" id="exampleModal" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
                                    <div class="modal-dialog">
                                    <div class="modal-content">
                                        <div class="modal-header">
                                            <h5 class="modal-title" id="exampleModalLabel">Delete customer</h5>
                                            <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                                                <span aria-hidden="true">&times;</span>
                                            </button>
                                        </div>
                                        <div id="updateThisText" class="modal-body">
                                            Are you sure you want to delete the customer: {{c.name}}
                                        </div>
                                        <div class="modal-footer">
                                            <button type="button" class="btn btn-secondary" data-dismiss="modal">Cancel</button>
                                            <a id="updateThisURL" href="{% url 'customers:customers_delete' c.id %}" class="text-decoration-none">
                                                <button type="button"  class="btn btn-danger">Delete</button>
                                            </a>
                                        </div>
                                    </div>
                                    </div>
                                </div>
                            </td>
                        </tr>
                        {% endfor %}
                    </tbody>
                </table>
            </div>
        </div>
    </div>
{% endblock content %}

<!-- Specific Page JS goes HERE  -->
{% block javascripts %}
<!-- Datatables -->
<script src="{% static 'vendor/datatables/jquery.dataTables.min.js' %}"></script>
<script src="{% static 'vendor/datatables/dataTables.bootstrap4.min.js' %}"></script>
<!--Datatable buttons-->
<script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/jszip/2.5.0/jszip.min.js"></script>
<script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/pdfmake/0.1.36/pdfmake.min.js"></script>
<script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/pdfmake/0.1.36/vfs_fonts.js"></script>
<script type="text/javascript" src="https://cdn.datatables.net/1.13.1/js/jquery.dataTables.min.js"></script>
<script type="text/javascript" src="https://cdn.datatables.net/buttons/2.3.3/js/dataTables.buttons.min.js"></script>
<script type="text/javascript" src="https://cdn.datatables.net/buttons/2.3.3/js/buttons.colVis.min.js"></script>
<script type="text/javascript" src="https://cdn.datatables.net/buttons/2.3.3/js/buttons.html5.min.js"></script>
<script type="text/javascript" src="https://cdn.datatables.net/buttons/2.3.3/js/buttons.print.min.js"></script>
<!--Moment JS-->
<script type="text/javascript" src="https://cdn.jsdelivr.net/momentjs/latest/moment.min.js"></script>

<!--Datatables-->
<script>
    // Call the dataTables jQuery plugin
    $(document).ready(function() {
        tblCategories = $('#dataTable').DataTable({
            dom: 'Bfrtip', // Buttons are draw at this element
            buttons: [
                {
                extend: 'print',
                text: 'Print <i class="fas fa-file ml-2"></i>',
                titleAttr: 'Print',
                className: 'btn btn-info',
                exportOptions: {
                    columns: [ 0, 1, 2, 3 ,4 ]
                }            
                },
                {
                    extend: 'excelHtml5',
                    text: 'Download Excel <i class="fas fa-file-excel ml-2"></i>',
                    titleAttr: 'Download Excel',
                    className: 'btn btn-success ml-2',
                    exportOptions: {
                        columns: [ 0, 1, 2, 3 ,4 ]
                    } 
                },
                {
                    extend: 'pdfHtml5',
                    text: 'Download PDF <i class="fas fa-file-pdf ml-2"></i>',
                    titleAttr: 'Download PDF',
                    className: 'btn btn-danger ml-2',
                    download: 'open',
                    orientation: 'vertical',
                    pageSize: 'A4',
                    title: '*',
                    exportOptions: {
                        columns: [ 0, 1, 2, 3 ,4 ]
                    },
                    customize: function (doc) {
                        doc.styles = {
                            header: {
                                fontSize: 18,
                                bold: true,
                                alignment: 'center'
                            },
                            subheader: {
                                fontSize: 13,
                                bold: true
                            },
                            quote: {
                                italics: true
                            },
                            small: {
                                fontSize: 8
                            },
                            tableHeader: {
                                bold: true,
                                fontSize: 11,
                                color: 'white',
                                fillColor: '#2d4154',
                                alignment: 'center'
                            }
                        };
                        doc.content[1].table.widths = ['10%', '10%', '30%', '30%', '20%'];
                        doc.content[1].margin = [0, 35, 0, 0];
                        doc.content[1].layout = {};
                        doc['footer'] = (function (page, pages) {
                            return {
                                columns: [
                                    {
                                        alignment: 'left',
                                        text: ['Creation date: ', {text: moment().format('MM-DD-YYYY (HH:mm:ss)')}]
                                    },
                                    {
                                        alignment: 'right',
                                        text: ['page ', {text: page.toString()}, ' de ', {text: pages.toString()}]
                                    }
                                ],
                                margin: 20
                            }
                        });

                    }
                }
            ],
            deferRender: true,
            columnDefs: [
                {
                    targets: [0],
                    visible: false,
                    searchable: false,
                },
                {
                    targets: [-1], // column index (start from 0)
                    orderable: false, // set orderable false for selected columns
                }
            ],
        });
    });

    // Alert when trying to delete a customer
    $('#dataTable tbody')
    // Event when whe try to delete a customer
    // We update the text, and href of the modal delete button
    .on('click', 'button[rel="delete"]', function () {
    // Row variable
    var tr = tblCategories.cell($(this).closest('td, li')).index();
    row_data = ( tblCategories.row(tr.row).data());
    customer_id = row_data[0];
    customer_name = row_data[2]
    new_delete_url  = 'delete/' + customer_id;
    document.getElementById("updateThisText").innerHTML = "Are you sure you want to delete the customer:  " + customer_name + "?";
    document.getElementById("updateThisURL").href=new_delete_url;
    });
</script>
{% endblock javascripts %}

django_pos/templates/customers/customers_add.html
{% extends "pos/base.html" %}

<!-- Page title  -->
{% block title %}Add customer{% endblock title %}

<!-- Specific Page CSS goes HERE  -->
{% block stylesheets %}{% endblock stylesheets %}

<!-- Page Heading -->
{% block heading %}Add customer{% endblock heading %}

<!-- Page content  -->
{% block content %}
<!--Go back-->
<div class="row ml-0 mb-3">
    <a href="{% url 'customers:customers_list' %}">
        <button type="button" class="btn btn-info font-weight-bold">
            <i class="fas fa-long-arrow-alt-left mr-2"></i>
            Go back
        </button>
    </a>
</div>

<div class="row">
    <div class="card col-md-8">
        <div class="card-body">
            <form action="{% url 'customers:customers_add' %}"  method="post">
                {% csrf_token %}
                <div class="form-row">
                    <div class="form-group col-md-6">
                        <label for="inputDescription">First Name</label>
                        <input type="text" class="form-control" name="first_name" placeholder="John..." required>
                    </div>
                    <div class="form-group col-md-6">
                        <label for="inputDescription">Last Name</label>
                        <input type="text" class="form-control" name="last_name" placeholder="Doe..." required>
                    </div>
                </div>

                <div class="form-row">
                    <div class="form-group col-md-6">
                        <label for="inputDescription">Email</label>
                        <input type="email" name="email" class="form-control" placeholder="johndoe@gmail.com" required>
                    </div>
                    <div class="form-group col-md-6">
                        <label for="inputDescription">Phone number</label>
                        <input type="text" name="phone" class="form-control" placeholder="(412) 727-2736" required>
                    </div>
                </div>

                <div class="form-row">
                    <div class="form-group col-md-12">
                        <label for="inputDescription">Address</label>
                        <textarea name="address" class="form-control" placeholder="5340 Brett Dr #A Fort Knox, Kentucky(KY), 40121 ..." rows="2" required></textarea>
                    </div>
                </div>
                

                <button type="submit" class="btn btn-success font-weight-bold">Create customer</button>
               
            </form>
        </div>
    </div>
</div>
{% endblock content %}

<!-- Specific Page JS goes HERE  -->
{% block javascripts %}{% endblock javascripts %}

django_pos/templates/customers/customers_update.html
{% extends "pos/base.html" %}

<!-- Page title  -->
{% block title %}Update customer{% endblock title %}

<!-- Specific Page CSS goes HERE  -->
{% block stylesheets %}{% endblock stylesheets %}

<!-- Page Heading -->
{% block heading %}Update customer{% endblock heading %}

<!-- Page content  -->
{% block content %}
<!--Go back-->
<div class="row ml-0 mb-3">
    <a href="{% url 'customers:customers_list' %}">
        <button type="button" class="btn btn-info font-weight-bold">
            <i class="fas fa-long-arrow-alt-left mr-2"></i>
            Go back
        </button>
    </a>
</div>

<div class="row">
    <div class="card col-md-8">
        <div class="card-body">
            <form action="{% url 'customers:customers_update' customer.id %}"  method="post">
                {% csrf_token %}
                <div class="form-row">
                    <div class="form-group col-md-6">
                        <label for="inputDescription">First Name</label>
                        <input type="text" class="form-control" name="first_name" value="{{customer.first_name}}" required>
                    </div>
                    <div class="form-group col-md-6">
                        <label for="inputDescription">Last Name</label>
                        <input type="text" class="form-control" name="last_name" value="{{customer.last_name}}" required>
                    </div>
                </div>

                <div class="form-row">
                    <div class="form-group col-md-6">
                        <label for="inputDescription">Email</label>
                        <input type="email" name="email" class="form-control" value="{{customer.email}}" required>
                    </div>
                    <div class="form-group col-md-6">
                        <label for="inputDescription">Phone number</label>
                        <input type="text" name="phone" class="form-control" value="{{customer.phone}}" required>
                    </div>
                </div>

                <div class="form-row">
                    <div class="form-group col-md-12">
                        <label for="inputDescription">Address</label>
                        <textarea name="address" class="form-control" rows="2" required>{{customer.address}}</textarea>
                    </div>
                </div>
                

                <button type="submit" class="btn btn-success font-weight-bold">Update customer</button>
               
            </form>
        </div>
    </div>
</div>
{% endblock content %}

<!-- Specific Page JS goes HERE  -->
{% block javascripts %}{% endblock javascripts %}